# -*- mode: ruby -*-
# vi: set ft=ruby :

#FILE
# vagrant/Vagrantfile.newbox
#PURPOSE
#	Create an intermediate base box from Xenial for
#	development use. Saves downloading while developing base Vagrantfile.
#PROVIDES
#	Ubuntu Xenial VM Docker Compose production ready
#USE
#	cd vagrant; VAGRANT_VAGRANTFILE=Vagrantfile.newbox vagrant up
#	vagrant package --output xenial64pip.box
#	vagrant box add xenial64pip xenial64pip.box
#AUTHOR
# (C) 2016 Gary Wallis unxs@unxs.io for Adhoc Engineering S.A.

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.ssh.insert_ssh_key = false

  config.vm.provider :virtualbox do |vb|
	vb.name = "adhoc0"
	config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2
  end

  config.vm.provision "shell", inline: <<-SHELL

	grep -q 'mesg n' /root/.profile && sed -i '/mesg n/d' /root/.profile && echo 'Ignore the previous error...';
	apt-get update --assume-yes;
	if [ "$?" != "0" ];then
          echo "apt-get update failed";
          exit 1;
	fi
        apt-get upgrade --assume-yes;
	if [ "$?" != "0" ];then
          echo "apt-get upgrade failed";
          exit 1;
	fi
	apt-get install python-pip --assume-yes;
	if [ "$?" != "0" ];then
          echo "python-pip install failed";
          exit 1;
	fi
        pip install --upgrade docker-compose;
	if [ "$?" != "0" ];then
          echo "pip install failed";
          exit 1;
	fi
        curl -sSL https://get.docker.com/ | /bin/bash;
	if [ "$?" != "0" ];then
          echo "docker script failed";
          exit 1;
	fi
        #groupadd docker; gpasswd -a ubuntu docker;
        systemctl enable docker;
	if [ "$?" != "0" ];then
          echo "docker systemd enabled failed";
          exit 1;
	fi
        systemctl start docker;
	if [ "$?" != "0" ];then
          echo "docker systemd start failed";
          exit 1;
	fi
	systemctl stop docker;

	#clean up to keep small
	sudo apt-get clean;
	dd if=/dev/zero of=/EMPTY bs=1M;
	rm -f /EMPTY;
	cat /dev/null > ~/.bash_history && history -c;
  SHELL
end
