# -*- mode: ruby -*-
# vi: set ft=ruby :

#FILE
# vagrant/vagrant.dev/Vagrantfile
#PURPOSE
# Build a docker-compose Odoo VM and Docker images quasi deterministicly.
# Useful for testing and for base for building production images.
#PROVIDES
#	Ubuntu Xenial VM Docker Compose production ready
#	Automatic nginx reverse proxy
#	Odoo ERP w/DB in separate container
#USE
#	cd vagrant/vagrant.dev; vagrant up
#	For VM guests on Ubuntu Xenial
#	Requires Virtual box host only nework vboxnet0 setup with virtual box dhcp server
#	running on host. And you may need to run:
#	$ VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0
#AUTHOR
# (C) 2016 Gary Wallis unxs@unxs.io for Adhoc Engineering S.A.

Vagrant.configure("2") do |config|

  config.vm.box = "xenial64pip"
  config.ssh.username = "ubuntu"

  config.vm.provider :virtualbox do |vb|
	vb.name = "adhoc0-dev"
	config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2
  end

  config.vm.provision "shell", inline: <<-SHELL

	echo "check network";
	ping -c 1 8.8.8.8 > /dev/null 2>&1;
	if [ "$?" != "0" ];then
		echo "configure network";
		ifconfig enp0s8 172.28.128.3 netmask 255.255.255.0 up;
		route add default gw 172.28.128.1 enp0s8;
	fi

	echo "download dev unxs0 github repo";
	rm -rf docker-odoo-adhoc; 
        git clone https://github.com/unxs0/docker-odoo-adhoc.git;
	if [ "$?" != "0" ];then
          echo "git clone failed";
          exit 1;
	fi
	#this creates the dockernginxadhox_backend network
	#it must be created once and before any other containers.
	#automated reverse proxy nginx-proxy
	echo "nginx startup";
	cd docker-odoo-adhoc/docker-nginx-adhoc;
	docker-compose up -d;
	if [ "$?" != "0" ];then
          echo "docker-compose up nginx failed";
          exit 1;
	fi

	#start db and odoo
	echo "db and odoo startup";
	cd ..;
	docker-compose up -d;
	if [ "$?" != "0" ];then
          echo "docker-compose up odoo failed";
          exit 1;
	fi

	#make docker containers persist reboot
	docker update --restart=always dockerodooadhoc_odoo_1;
	docker update --restart=always dockerodooadhoc_db_1;
	docker update --restart=always nginx-proxy;
	echo "odoo available on port 8069 local and via nginx on port 80";
  SHELL
end
